name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - '.github/workflows/deploy.yml'
      - 'server.js'
      - 'load-test.js'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Esta etapa faz o checkout do código do repositório GitHub.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Esta etapa configura as credenciais da AWS usando os segredos armazenados no GitHub.

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        # Esta etapa configura o Terraform no ambiente de execução.

      - name: Terraform Init
        run: terraform init
        # Esta etapa inicializa o Terraform, baixando os plugins necessários e preparando o ambiente.

      - name: Terraform Plan
        id: plan
        run: terraform plan -target=aws_api_gateway_rest_api.my_api_gateway -out=tfplan
        # Esta etapa cria um plano de execução do Terraform para verificar as mudanças no recurso especificado.

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        # Esta etapa aplica as configurações do Terraform usando o plano gerado, criando ou atualizando os recursos definidos no arquivo main.tf.

      - name: Verify Terraform Output
        run: |
          terraform output -json api_gateway_url > output.json || echo '{"value": "default_url"}' > output.json
          cat output.json
        # Esta etapa verifica a saída do comando terraform output -json e define um valor padrão se o output não for encontrado.

      - name: Add k6 repository
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo wget -q -O - https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee -a /etc/apt/sources.list.d/k6.list
          sudo apt-get update
        # Esta etapa adiciona o repositório oficial do k6 no GitHub.

      - name: Install k6
        run: sudo apt-get install -y k6
        # Esta etapa instala o k6 no ambiente de execução.

      - name: Run load test
        run: |
          API_URL=$(cat output.json | jq -r '.value')
          k6 run load-test.js --summary-trend-stats "avg,med,min,max,p(90),p(95)" --out json=resultado.json --env API_URL=$API_URL
        # Esta etapa executa o teste de carga usando o k6, exibe métricas e exporta o relatório em JSON.
