name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - '.github/workflows/deploy.yml'
      - 'server.js'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Esta etapa faz o checkout do código do repositório GitHub.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Esta etapa configura as credenciais da AWS usando os segredos armazenados no GitHub.

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        # Esta etapa configura o Terraform no ambiente de execução.

      - name: Terraform Init
        run: terraform init
        # Esta etapa inicializa o Terraform, baixando os plugins necessários e preparando o ambiente.

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        # Esta etapa cria um plano de execução do Terraform para verificar as mudanças.

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        # Esta etapa aplica as configurações do Terraform usando o plano gerado, criando ou atualizando os recursos definidos no arquivo main.tf.

      - name: Set API URL
        id: set_api_url
        run: echo "API_URL=$(terraform output -raw api_gateway_url)" >> $GITHUB_ENV
        # Esta etapa captura a saída do Terraform e define a variável de ambiente API_URL.
