name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - '.github/workflows/deploy.yml'
      - 'server.js'
      - 'load-test.js'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Esta etapa faz o checkout do código do repositório GitHub.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        # Esta etapa configura as credenciais da AWS usando os segredos armazenados no GitHub.

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        # Esta etapa configura o Terraform no ambiente de execução.

      - name: Terraform Init
        run: terraform init
        # Esta etapa inicializa o Terraform, baixando os plugins necessários e preparando o ambiente.

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # Esta etapa aplica as configurações do Terraform, criando ou atualizando os recursos definidos no arquivo main.tf.

      - name: Add k6 repository
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 33D40BC6
          echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
        # Esta etapa adiciona o repositório oficial do k6.

      - name: Install k6
        run: sudo apt-get install -y k6
        # Esta etapa instala o k6 no ambiente de execução.

      - name: Run load test
        run: k6 run load-test.js
        # Esta etapa executa o teste de carga usando o k6.
